config/routes.rb
Rails.application.routes.draw do
  get 'comments/new'

  get 'comments/edit'

  get 'comments/create'

  get 'topics/new'

  get 'topics/show'

  get 'topics/edit'

  get 'categories/show'

  get 'informations/show'

  get 'sessions/new'

  get 'users/new'

  root             'categories#index'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'home2' => 'static_pages#home'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'signup'  => 'users#new'

  resources :users
  resources :informations
  resources :categories
  resources :topics
  resources :comments

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :comments
  validates :title, presence: true,
            length: {in: 30..150}
  validates :content, presence: true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :edit, :update]  #need log in to access this site
  before_action :correct_user_topic,   only: [:edit, :update]   #Can not change the data of other user

  def index
    @category = Category.find(params[:id])
    @topic = @category.topics.all
  end

  def new
    @topic = Topic.new
  end

  def create
    @user = current_user
    @topic = @user.topics.new(params_topic)
    if @topic.save
      flash[:success] = "Create new topic success!"
      redirect_to @topic
    else
      render 'new'
    end
  end
  def show
    @topic = Topic.find(params[:id])
    @user = User.find_by_id(@topic.user_id)
    @info = @user.information
    @category = Category.find_by_id(@topic.category_id)
    @comment = @topic.comments.all
    @new_comment = Comment.new
    @user_now = current_user
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])
    if @topic.update_attributes(params_topic)
      flash[:success] = "Update success"
      redirect_to @topic
    else
      render 'edit'
    end
  end


  private

  def params_topic
    params.require(:topic).permit(:title, :content, :category_id)
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/edit.html.erb
<% provide(:title, "Edit topic") %>

<div class="container">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="breadcrumb">Edit topic</h1>
    <%= form_for (@topic) do |f| %>
        <%= render 'shared/error_topic_messages' %>

        <%= f.label :title, "Title" %>
        <%= f.text_field :title, class: "form-control" %>

        <%= f.label :content, "Content" %>
        <%= f.text_area :content, class: "form-control" %>

        <div class="col-md-4"><%= f.submit "Create new topic", class: "btn btn-primary" %></div>
    <% end %>
  </div>
</div>

app/views/topics/index.html.erb
<% provide(:title, @category.name) %>
<div class="container">
  <% @topic.each do |topic| %>
      <!--<div class="row">-->
      <div class="center jumbotron">
        <div class="col-md-4"><b><%= link_to topic.title, topic %></b></div>
        <div class="col-md-8">0 Comment</div>

        <!--</div>-->
        <br>
      </div>
  <% end %>
</div>

app/views/topics/new.html.erb
<% provide(:title, "New topic") %>

<div class="container">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="breadcrumb">Create new topic</h1>
    <%= form_for (@topic) do |f| %>
      <%= render 'shared/error_topic_messages' %>

      <%= f.label :category, "Choose the Category which you want" %>
      <%= f.collection_select(:category_id,  Category.all, :id, :name) %>

      <%= f.label :title, "Title" %>
      <%= f.text_field :title, class: "form-control" %>

      <%= f.label :content, "Content" %>
      <%= f.text_area :content, class: "form-control" %>

      <div class="col-md-4"><%= f.submit "Create new topic", class: "btn btn-primary" %></div>
    <% end %>
  </div>
</div>

app/views/topics/show.html.erb
<% provide(:title, @topic.title) %>
<div class="container">

  <div class="col-md-8">

    <div class="breadcrumb">
      <% if logged_in? %>
          Create new topic at <%= link_to "here", new_topic_path%>
      <% else %>
          You need <%= link_to "Log in", login_path%> or <%= link_to "Sign up", signup_path%> to create a new topic!
      <% end %>
    </div>

    <ol class = "breadcrumb">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to @category.name, @category %></li>
    </ol>

    <div class = "panel panel-default">
      <div class = "panel-heading">
        <h3 class = "panel-title">
          <b align = "center">[<%= link_to @category.name, @category %>] <%= @topic.title%></b>
        </h3>
        </div>

      <div class = "panel-body">
        <div class="col-md-3 center">
          <%= image_tag(@info.avatar.url(:thumb)) %><br>
          <%= link_to @user.name, @user %><br>
          <%=  pluralize(@user.topics.count + @user.comments.count, "post") %>
        </div>
        <div class="col-md-9"><%= @topic.content %></div>
      </div>

      <div class = "panel-body">
        <hr>
        <div class="col-md-4">
          <%= link_to "Edit", edit_topic_path%>
        </div>
        <div class="col-md-7"><i>Created at: <%= @topic.created_at %></i></div>
        <div class="col-md-1"><i>#1</i></div>
      </div>
    </div>
    <% count = 2 %>
    <% @comment.each do |t| %>
        <% user_comment = User.find_by_id(t.user_id) %>
        <div class = "panel panel-default">
          <div class = "panel-body">
            <div class="col-md-3 center">
              <%= image_tag(user_comment.information.avatar.url(:thumb)) %><br>
              <%= link_to user_comment.name, user_comment %><br>
              <%=  pluralize(user_comment.topics.count + user_comment.comments.count, "post") %>
            </div>
            <div class="col-md-9"><%= t.content %></div>
          </div>
          <div class = "panel-body">
            <hr>
            <div class="col-md-4">
              <%= link_to "edit", edit_comment_path(t)%>
            </div>
            <div class="col-md-7"><i>Created at: <%= t.created_at %></i></div>
            <div class="col-md-1"><i>#<%= count%></i></div>
          </div>
        </div>
        <% count = count + 1 %>
    <%end%>

    <div class = "panel panel-default">
      <div class = "panel-heading">
        <h3 class = "panel-title">
          <b>Add a comment</b>
        </h3>
      </div>

      <div class = "panel-body">
        <% if logged_in? %>
            <div class="col-md-3 center">
              <%= image_tag(@user_now.information.avatar.url(:thumb)) %><br>
            </div>

            <%= form_for @new_comment do |f| %>
                <%= render 'shared/error_comment_messages' %>
                <div class="col-md-7 center">
                <%= f.text_area :content%>
                 <%= f.radio_button :topic_id, @topic.id,checked: true%>

                  </div>
                  <div class="col-md-2">
                <%= f.submit "Save", class: "btn btn-primary"%></div>
                <% end %>
            </div>
        <% else %>
            You need <%= link_to "Log in", login_path%> or <%= link_to "Sign up", signup_path%> to add a comment!
        <% end %>



      </div>
    </div>
  </div>
</div>