config/routes.rb
Rails.application.routes.draw do
  get 'comments/new'

  get 'comments/edit'

  get 'comments/create'

  get 'topics/new'

  get 'topics/show'

  get 'topics/edit'

  get 'categories/show'

  get 'informations/show'

  get 'sessions/new'

  get 'users/new'

  root             'categories#index'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'home2' => 'static_pages#home'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'signup'  => 'users#new'

  resources :users
  resources :informations
  resources :categories
  resources :topics
  resources :comments

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Noname - team 2016<br>
    UET - VNU
  </small>
  <nav>
    <ul>
      <li><%= link_to "Help", help_path %></li>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Noname Forum", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-left">
        <% Category.all.each do |t| %>
        <li><%= link_to t.name, t %></li>
            <% end %>

      </ul>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Wellcome, <%=current_user.name%> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_information_path(current_user)%></li>
                <li><%= link_to "Change password", edit_user_path(current_user)%></li>
                <li class="divider"></li>
                <li><%= link_to "Log out", logout_path, method: "delete" %></li>
              </ul>
            </li>
            <li><% @info = current_user.information %></li>
            <div class="round-image-50"><%= image_tag(@info.avatar.url(:thumb)) %></div>
        <% else %>
            <li><a href="/signup"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
            <li><a href="/login"><span class="glyphicon glyphicon-log-in"></span> Log In</a></li>
            <% if false %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-log-in"> </span> Login</a>
              <ul class="dropdown-menu">
                <div class="">
                  <div class="col-md-12">
                <%= form_for(:session, url: login_path) do |f| %>

                    <%= f.label :email %>
                    <%= f.email_field :email, class: 'form-control' %>

                    <%= f.label :password %>
                    <%= f.password_field :password, class: 'form-control' %>

                    <%= f.label :remember_me, class: "checkbox inline" do %>
                        <%= f.check_box :remember_me %>
                        <span>Remember me on this computer</span>
                    <% end %>

                    <%= f.submit "Log in", class: "btn btn-primary" %>
                <% end %>
                      </div></div>
              </ul>
            </li>
                <% end %>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%= yield(:title) %> | Noname Forum</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
<%= yield %>
  <%= render 'layouts/footer' %>
</div>
</body>
</html>